-- =====================================================
-- Purpose:
--   Learning/MVP Lean PostgreSQL schema for a customer commerce app.
--
-- Scope:
--   Schema only.
--   No triggers.
--   No views.
--   No functions.
--   No seed/test data.
--
-- =====================================================

DROP SCHEMA IF EXISTS customer_app CASCADE;
CREATE SCHEMA customer_app;
SET search_path TO customer_app, public;


-- =====================================================
-- 0. ENUM TYPES
-- =====================================================

CREATE TYPE user_status_t AS ENUM ('active', 'inactive', 'suspended');
CREATE TYPE address_type_t AS ENUM ('shipping', 'billing', 'other');

CREATE TYPE shop_status_t AS ENUM ('active', 'inactive', 'suspended', 'closed');
CREATE TYPE product_status_t AS ENUM ('draft', 'active', 'inactive', 'out_of_stock', 'discontinued');

CREATE TYPE cart_status_t AS ENUM ('active', 'checked_out', 'abandoned');

CREATE TYPE discount_type_t AS ENUM ('fixed', 'percent');

CREATE TYPE order_status_t AS ENUM (
    'draft',
    'pending_payment',
    'confirmed',
    'processing',
    'shipped',
    'delivered',
    'completed',
    'cancelled'
);

CREATE TYPE payment_status_t AS ENUM (
    'pending',
    'paid',
    'failed',
    'partially_refunded',
    'refunded',
    'cancelled'
);

CREATE TYPE shipment_status_t AS ENUM (
    'pending',
    'packed',
    'picked_up',
    'in_transit',
    'delivered',
    'failed',
    'returned',
    'cancelled'
);

CREATE TYPE return_status_t AS ENUM (
    'requested',
    'approved',
    'rejected',
    'received',
    'refunded',
    'cancelled'
);

CREATE TYPE refund_status_t AS ENUM (
    'pending',
    'processing',
    'completed',
    'failed',
    'cancelled'
);

CREATE TYPE review_target_t AS ENUM ('product', 'shop');
CREATE TYPE review_status_t AS ENUM ('pending', 'approved', 'rejected');


-- =====================================================
-- 1. CUSTOMER IDENTITY
-- =====================================================

CREATE TABLE app_users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_user_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),

    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(120) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,

    first_name VARCHAR(80),
    last_name VARCHAR(80),
    phone_number VARCHAR(30),

    status user_status_t NOT NULL DEFAULT 'active',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMP,

    CONSTRAINT chk_app_users_username_not_blank
        CHECK (length(trim(username)) >= 3),

    CONSTRAINT chk_app_users_email_format
        CHECK (email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$')
);

CREATE TABLE user_addresses (
    address_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES app_users(user_id) ON DELETE CASCADE,

    address_type address_type_t NOT NULL DEFAULT 'shipping',
    recipient_name VARCHAR(120) NOT NULL,
    phone_number VARCHAR(30) NOT NULL,

    street VARCHAR(255) NOT NULL,
    ward VARCHAR(100),
    district VARCHAR(100),
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100),
    postal_code VARCHAR(30),
    country VARCHAR(100) NOT NULL DEFAULT 'Vietnam',

    is_default_shipping BOOLEAN NOT NULL DEFAULT FALSE,
    is_default_billing BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE(user_id, address_id),

    CONSTRAINT chk_user_addresses_recipient_not_blank
        CHECK (length(trim(recipient_name)) > 0),

    CONSTRAINT chk_user_addresses_phone_not_blank
        CHECK (length(trim(phone_number)) > 0),

    CONSTRAINT chk_user_addresses_street_not_blank
        CHECK (length(trim(street)) > 0),

    CONSTRAINT chk_user_addresses_city_not_blank
        CHECK (length(trim(city)) > 0),

    CONSTRAINT chk_user_addresses_country_not_blank
        CHECK (length(trim(country)) > 0)
);

CREATE UNIQUE INDEX uq_user_default_shipping_address
ON user_addresses(user_id)
WHERE is_default_shipping = TRUE;

CREATE UNIQUE INDEX uq_user_default_billing_address
ON user_addresses(user_id)
WHERE is_default_billing = TRUE;


-- =====================================================
-- 2. SHOP AND PRODUCT CATALOG
-- =====================================================

CREATE TABLE shops (
    shop_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_shop_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),

    shop_name VARCHAR(160) NOT NULL,
    shop_slug VARCHAR(160) NOT NULL UNIQUE,
    description TEXT,
    logo_url VARCHAR(255),

    status shop_status_t NOT NULL DEFAULT 'active',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_shops_name_not_blank
        CHECK (length(trim(shop_name)) > 0),

    CONSTRAINT chk_shops_slug_not_blank
        CHECK (length(trim(shop_slug)) > 0)
);

CREATE TABLE categories (
    category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_category_id INTEGER REFERENCES categories(category_id) ON DELETE SET NULL,

    category_name VARCHAR(140) NOT NULL,
    slug VARCHAR(140) NOT NULL UNIQUE,
    description TEXT,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_categories_name_not_blank
        CHECK (length(trim(category_name)) > 0),

    CONSTRAINT chk_categories_slug_not_blank
        CHECK (length(trim(slug)) > 0),

    CONSTRAINT chk_categories_not_self_parent
        CHECK (parent_category_id IS NULL OR parent_category_id <> category_id)
);

CREATE TABLE products (
    product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_product_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),

    shop_id INTEGER NOT NULL REFERENCES shops(shop_id),
    category_id INTEGER NOT NULL REFERENCES categories(category_id),

    product_sku VARCHAR(100) NOT NULL UNIQUE,
    product_slug VARCHAR(220) NOT NULL UNIQUE,
    product_name VARCHAR(220) NOT NULL,

    short_description VARCHAR(512),
    description TEXT,
    brand VARCHAR(120),

    -- Replaces the previous category_attribute_* and product_attribute_values tables.
    -- Keep common searchable fields as real columns; keep flexible learning/MVP metadata here.
    attributes_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    images_json JSONB NOT NULL DEFAULT '[]'::JSONB,

    status product_status_t NOT NULL DEFAULT 'draft',
    is_featured BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE(product_id, shop_id),

    CONSTRAINT chk_products_sku_not_blank
        CHECK (length(trim(product_sku)) > 0),

    CONSTRAINT chk_products_slug_not_blank
        CHECK (length(trim(product_slug)) > 0),

    CONSTRAINT chk_products_name_not_blank
        CHECK (length(trim(product_name)) > 0),

    CONSTRAINT chk_products_attributes_is_object
        CHECK (jsonb_typeof(attributes_json) = 'object'),

    CONSTRAINT chk_products_images_is_array
        CHECK (jsonb_typeof(images_json) = 'array')
);

CREATE TABLE product_variants (
    product_variant_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_variant_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),

    product_id INTEGER NOT NULL REFERENCES products(product_id) ON DELETE CASCADE,

    variant_sku VARCHAR(120) NOT NULL UNIQUE,
    variant_name VARCHAR(220) NOT NULL,

    -- Replaces the previous option group/value bridge tables.
    options_json JSONB NOT NULL DEFAULT '{}'::JSONB,

    unit_price DECIMAL(12,2) NOT NULL CHECK (unit_price >= 0),
    compare_at_price DECIMAL(12,2) CHECK (compare_at_price IS NULL OR compare_at_price >= unit_price),
    currency CHAR(3) NOT NULL DEFAULT 'VND',

    -- Replaces variant_inventory for this learning/MVP schema.
    stock_quantity INTEGER NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0),
    reserved_quantity INTEGER NOT NULL DEFAULT 0 CHECK (reserved_quantity >= 0),

    weight_kg DECIMAL(8,3) CHECK (weight_kg IS NULL OR weight_kg >= 0),
    dimensions_json JSONB,
    images_json JSONB NOT NULL DEFAULT '[]'::JSONB,

    status product_status_t NOT NULL DEFAULT 'active',
    is_default BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE(product_variant_id, product_id),

    CONSTRAINT chk_variants_sku_not_blank
        CHECK (length(trim(variant_sku)) > 0),

    CONSTRAINT chk_variants_name_not_blank
        CHECK (length(trim(variant_name)) > 0),

    CONSTRAINT chk_variants_currency_format
        CHECK (currency ~ '^[A-Z]{3}$'),

    CONSTRAINT chk_variants_options_is_object
        CHECK (jsonb_typeof(options_json) = 'object'),

    CONSTRAINT chk_variants_images_is_array
        CHECK (jsonb_typeof(images_json) = 'array')
);

CREATE UNIQUE INDEX uq_default_variant_per_product
ON product_variants(product_id)
WHERE is_default = TRUE;


-- =====================================================
-- 3. CART
-- =====================================================

CREATE TABLE shopping_carts (
    cart_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id INTEGER NOT NULL REFERENCES app_users(user_id) ON DELETE CASCADE,

    status cart_status_t NOT NULL DEFAULT 'active',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uq_active_cart_per_user
ON shopping_carts(user_id)
WHERE status = 'active';

CREATE TABLE cart_items (
    cart_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    cart_id INTEGER NOT NULL REFERENCES shopping_carts(cart_id) ON DELETE CASCADE,
    product_variant_id INTEGER NOT NULL REFERENCES product_variants(product_variant_id),

    quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),

    unit_price_snapshot DECIMAL(12,2) NOT NULL DEFAULT 0 CHECK (unit_price_snapshot >= 0),
    currency CHAR(3) NOT NULL DEFAULT 'VND',

    added_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE(cart_id, product_variant_id),

    CONSTRAINT chk_cart_items_currency_format
        CHECK (currency ~ '^[A-Z]{3}$')
);


-- =====================================================
-- 4. VOUCHERS
-- =====================================================

CREATE TABLE vouchers (
    voucher_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    voucher_code VARCHAR(60) NOT NULL UNIQUE,
    voucher_name VARCHAR(160) NOT NULL,
    description TEXT,

    -- NULL shop_id means platform voucher; non-NULL means shop voucher.
    shop_id INTEGER REFERENCES shops(shop_id) ON DELETE CASCADE,

    discount_type discount_type_t NOT NULL,
    discount_value DECIMAL(12,2) NOT NULL CHECK (discount_value >= 0),
    max_discount_amount DECIMAL(12,2) CHECK (max_discount_amount IS NULL OR max_discount_amount >= 0),
    minimum_order_amount DECIMAL(12,2) NOT NULL DEFAULT 0 CHECK (minimum_order_amount >= 0),

    -- Replaces voucher_scopes. Example:
    -- {"type":"category","category_ids":[1,2]} or {"type":"all"}.
    scope_json JSONB NOT NULL DEFAULT '{"type":"all"}'::JSONB,

    starts_at TIMESTAMP,
    ends_at TIMESTAMP,

    usage_limit INTEGER CHECK (usage_limit IS NULL OR usage_limit >= 0),
    used_count INTEGER NOT NULL DEFAULT 0 CHECK (used_count >= 0),

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_voucher_time_window
        CHECK (starts_at IS NULL OR ends_at IS NULL OR ends_at > starts_at),

    CONSTRAINT chk_voucher_percent_value
        CHECK (
            discount_type = 'fixed'
            OR
            (discount_type = 'percent' AND discount_value <= 100)
        ),

    CONSTRAINT chk_voucher_used_count_within_limit
        CHECK (usage_limit IS NULL OR used_count <= usage_limit),

    CONSTRAINT chk_voucher_code_not_blank
        CHECK (length(trim(voucher_code)) > 0),

    CONSTRAINT chk_voucher_name_not_blank
        CHECK (length(trim(voucher_name)) > 0),

    CONSTRAINT chk_voucher_scope_is_object
        CHECK (jsonb_typeof(scope_json) = 'object')
);


-- =====================================================
-- 5. ORDERS
-- =====================================================

CREATE TABLE orders (
    order_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_order_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),

    customer_id INTEGER NOT NULL REFERENCES app_users(user_id),

    order_number VARCHAR(60) NOT NULL UNIQUE,

    order_status order_status_t NOT NULL DEFAULT 'draft',
    payment_status payment_status_t NOT NULL DEFAULT 'pending',

    shipping_address_id INTEGER NOT NULL,
    billing_address_id INTEGER NOT NULL,

    -- Snapshots protect order history when customer edits addresses later.
    shipping_address_snapshot JSONB NOT NULL,
    billing_address_snapshot JSONB NOT NULL,

    subtotal_amount DECIMAL(12,2) NOT NULL DEFAULT 0 CHECK (subtotal_amount >= 0),
    shipping_amount DECIMAL(12,2) NOT NULL DEFAULT 0 CHECK (shipping_amount >= 0),
    tax_amount DECIMAL(12,2) NOT NULL DEFAULT 0 CHECK (tax_amount >= 0),
    discount_amount DECIMAL(12,2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),

    total_amount DECIMAL(12,2)
        GENERATED ALWAYS AS (subtotal_amount + shipping_amount + tax_amount - discount_amount) STORED,

    currency CHAR(3) NOT NULL DEFAULT 'VND',
    customer_note TEXT,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE(order_id, customer_id),

    FOREIGN KEY (customer_id, shipping_address_id)
        REFERENCES user_addresses(user_id, address_id),

    FOREIGN KEY (customer_id, billing_address_id)
        REFERENCES user_addresses(user_id, address_id),

    CONSTRAINT chk_orders_discount_not_over_total_before_discount
        CHECK (discount_amount <= subtotal_amount + shipping_amount + tax_amount),

    CONSTRAINT chk_orders_total_non_negative
        CHECK (total_amount >= 0),

    CONSTRAINT chk_orders_currency_format
        CHECK (currency ~ '^[A-Z]{3}$'),

    CONSTRAINT chk_orders_number_not_blank
        CHECK (length(trim(order_number)) > 0)
);

CREATE TABLE order_items (
    order_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    order_id INTEGER NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,

    shop_id INTEGER NOT NULL REFERENCES shops(shop_id),
    product_id INTEGER NOT NULL,
    product_variant_id INTEGER NOT NULL,

    product_name_snapshot VARCHAR(220) NOT NULL,
    product_sku_snapshot VARCHAR(120) NOT NULL,
    variant_name_snapshot VARCHAR(220) NOT NULL,
    variant_sku_snapshot VARCHAR(120) NOT NULL,
    variant_options_snapshot JSONB NOT NULL DEFAULT '{}'::JSONB,

    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price DECIMAL(12,2) NOT NULL CHECK (unit_price >= 0),
    currency CHAR(3) NOT NULL DEFAULT 'VND',

    tax_amount DECIMAL(12,2) NOT NULL DEFAULT 0 CHECK (tax_amount >= 0),
    discount_amount DECIMAL(12,2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),

    item_subtotal DECIMAL(12,2)
        GENERATED ALWAYS AS (quantity * unit_price) STORED,

    item_total DECIMAL(12,2)
        GENERATED ALWAYS AS ((quantity * unit_price) + tax_amount - discount_amount) STORED,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (product_id, shop_id)
        REFERENCES products(product_id, shop_id),

    FOREIGN KEY (product_variant_id, product_id)
        REFERENCES product_variants(product_variant_id, product_id),

    UNIQUE(order_item_id, order_id),

    CONSTRAINT chk_order_items_discount_not_over_line_total
        CHECK (discount_amount <= quantity * unit_price + tax_amount),

    CONSTRAINT chk_order_items_total_non_negative
        CHECK (item_total >= 0),

    CONSTRAINT chk_order_items_currency_format
        CHECK (currency ~ '^[A-Z]{3}$'),

    CONSTRAINT chk_order_items_product_name_snapshot_not_blank
        CHECK (length(trim(product_name_snapshot)) > 0),

    CONSTRAINT chk_order_items_product_sku_snapshot_not_blank
        CHECK (length(trim(product_sku_snapshot)) > 0),

    CONSTRAINT chk_order_items_variant_name_snapshot_not_blank
        CHECK (length(trim(variant_name_snapshot)) > 0),

    CONSTRAINT chk_order_items_variant_sku_snapshot_not_blank
        CHECK (length(trim(variant_sku_snapshot)) > 0),

    CONSTRAINT chk_order_items_variant_options_is_object
        CHECK (jsonb_typeof(variant_options_snapshot) = 'object')
);

CREATE TABLE order_vouchers (
    order_voucher_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    order_id INTEGER NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
    voucher_id INTEGER NOT NULL REFERENCES vouchers(voucher_id),

    discount_amount DECIMAL(12,2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE(order_id, voucher_id)
);


-- =====================================================
-- 6. PAYMENT AND SHIPMENT
-- =====================================================

CREATE TABLE payments (
    payment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_payment_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),

    order_id INTEGER NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,

    payment_method VARCHAR(50) NOT NULL,
    payment_status payment_status_t NOT NULL DEFAULT 'pending',

    transaction_reference VARCHAR(160),
    amount DECIMAL(12,2) NOT NULL CHECK (amount >= 0),
    currency CHAR(3) NOT NULL DEFAULT 'VND',

    paid_at TIMESTAMP,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE(payment_id, order_id),

    CONSTRAINT chk_payments_method_not_blank
        CHECK (length(trim(payment_method)) > 0),

    CONSTRAINT chk_payments_currency_format
        CHECK (currency ~ '^[A-Z]{3}$')
);

CREATE UNIQUE INDEX uq_payments_transaction_reference
ON payments(payment_method, transaction_reference)
WHERE transaction_reference IS NOT NULL;

CREATE TABLE shipments (
    shipment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_shipment_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),

    order_id INTEGER NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,

    shipment_status shipment_status_t NOT NULL DEFAULT 'pending',

    carrier VARCHAR(100),
    tracking_number VARCHAR(160),

    shipping_address_snapshot JSONB NOT NULL,

    shipped_at TIMESTAMP,
    delivered_at TIMESTAMP,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE(shipment_id, order_id),

    CONSTRAINT chk_shipment_time_order
        CHECK (
            shipped_at IS NULL
            OR delivered_at IS NULL
            OR delivered_at >= shipped_at
        )
);

CREATE UNIQUE INDEX uq_shipments_tracking_number
ON shipments(carrier, tracking_number)
WHERE tracking_number IS NOT NULL;


-- =====================================================
-- 7. RETURNS AND REFUNDS
-- =====================================================

CREATE TABLE returns (
    return_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_return_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),

    -- One row is one returned order item line.
    -- return_group_id lets several returned lines belong to the same request.
    return_group_id UUID NOT NULL DEFAULT gen_random_uuid(),

    order_id INTEGER NOT NULL,
    order_item_id INTEGER NOT NULL,
    customer_id INTEGER NOT NULL,

    return_status return_status_t NOT NULL DEFAULT 'requested',

    quantity INTEGER NOT NULL CHECK (quantity > 0),
    reason TEXT NOT NULL,
    requested_amount DECIMAL(12,2) NOT NULL DEFAULT 0 CHECK (requested_amount >= 0),

    requested_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE(return_id, order_id),

    FOREIGN KEY (order_id, customer_id)
        REFERENCES orders(order_id, customer_id)
        ON DELETE CASCADE,

    FOREIGN KEY (order_item_id, order_id)
        REFERENCES order_items(order_item_id, order_id),

    CONSTRAINT chk_return_reason_not_blank
        CHECK (length(trim(reason)) > 0)
);

CREATE TABLE refunds (
    refund_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_refund_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),

    order_id INTEGER NOT NULL,
    return_id INTEGER,
    payment_id INTEGER,

    refund_status refund_status_t NOT NULL DEFAULT 'pending',

    amount DECIMAL(12,2) NOT NULL CHECK (amount >= 0),
    transaction_reference VARCHAR(160),

    refunded_at TIMESTAMP,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (return_id, order_id)
        REFERENCES returns(return_id, order_id),

    FOREIGN KEY (payment_id, order_id)
        REFERENCES payments(payment_id, order_id),

    CONSTRAINT chk_refund_has_source
        CHECK (return_id IS NOT NULL OR payment_id IS NOT NULL)
);

CREATE UNIQUE INDEX uq_refunds_transaction_reference
ON refunds(transaction_reference)
WHERE transaction_reference IS NOT NULL;


-- =====================================================
-- 8. REVIEWS
-- =====================================================

CREATE TABLE reviews (
    review_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    review_target review_target_t NOT NULL,

    order_id INTEGER NOT NULL,
    customer_id INTEGER NOT NULL,
    shop_id INTEGER NOT NULL REFERENCES shops(shop_id),

    -- Product reviews should reference a purchased line.
    -- Shop reviews can leave order_item_id/product_id/product_variant_id null.
    order_item_id INTEGER,
    product_id INTEGER,
    product_variant_id INTEGER,

    rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    title VARCHAR(160),
    review_text TEXT,
    images_json JSONB NOT NULL DEFAULT '[]'::JSONB,
    review_status review_status_t NOT NULL DEFAULT 'pending',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (order_id, customer_id)
        REFERENCES orders(order_id, customer_id),

    FOREIGN KEY (order_item_id, order_id)
        REFERENCES order_items(order_item_id, order_id),

    FOREIGN KEY (product_variant_id, product_id)
        REFERENCES product_variants(product_variant_id, product_id),

    CONSTRAINT chk_review_target_columns CHECK (
        (
            review_target = 'product'
            AND order_item_id IS NOT NULL
            AND product_id IS NOT NULL
            AND product_variant_id IS NOT NULL
        )
        OR
        (
            review_target = 'shop'
            AND order_item_id IS NULL
            AND product_id IS NULL
            AND product_variant_id IS NULL
        )
    ),

    CONSTRAINT chk_review_title_not_blank
        CHECK (title IS NULL OR length(trim(title)) > 0),

    CONSTRAINT chk_review_images_is_array
        CHECK (jsonb_typeof(images_json) = 'array')
);

CREATE UNIQUE INDEX uq_one_product_review_per_order_item
ON reviews(order_item_id)
WHERE review_target = 'product';

CREATE UNIQUE INDEX uq_one_shop_review_per_order_shop
ON reviews(order_id, shop_id)
WHERE review_target = 'shop';


-- =====================================================
-- 9. INDEXES FOR APP AND FUTURE DWH EXTRACTION
-- =====================================================

-- Composite watermark indexes used by deterministic incremental extraction:
-- WHERE updated_at >= :lower_bound AND updated_at <= :upper_bound
-- ORDER BY updated_at, <primary_key>.
CREATE INDEX idx_app_users_updated_id
ON app_users(updated_at, user_id);

CREATE INDEX idx_user_addresses_updated_id
ON user_addresses(updated_at, address_id);

CREATE INDEX idx_shops_updated_id
ON shops(updated_at, shop_id);

CREATE INDEX idx_categories_updated_id
ON categories(updated_at, category_id);

CREATE INDEX idx_products_updated_id
ON products(updated_at, product_id);

CREATE INDEX idx_product_variants_updated_id
ON product_variants(updated_at, product_variant_id);

CREATE INDEX idx_vouchers_updated_id
ON vouchers(updated_at, voucher_id);

CREATE INDEX idx_orders_updated_id
ON orders(updated_at, order_id);

CREATE INDEX idx_order_items_updated_id
ON order_items(updated_at, order_item_id);

CREATE INDEX idx_order_vouchers_updated_id
ON order_vouchers(updated_at, order_voucher_id);

CREATE INDEX idx_payments_updated_id
ON payments(updated_at, payment_id);

CREATE INDEX idx_shipments_updated_id
ON shipments(updated_at, shipment_id);

CREATE INDEX idx_user_addresses_user ON user_addresses(user_id);

CREATE INDEX idx_categories_parent ON categories(parent_category_id);

CREATE INDEX idx_products_shop ON products(shop_id);
CREATE INDEX idx_products_category ON products(category_id);
CREATE INDEX idx_products_status ON products(status);
CREATE INDEX idx_products_created ON products(created_at);
CREATE INDEX idx_products_attributes_gin ON products USING GIN (attributes_json);

CREATE INDEX idx_variants_product ON product_variants(product_id);
CREATE INDEX idx_variants_status ON product_variants(status);
CREATE INDEX idx_variants_options_gin ON product_variants USING GIN (options_json);

CREATE INDEX idx_carts_user_status ON shopping_carts(user_id, status);
CREATE INDEX idx_cart_items_cart ON cart_items(cart_id);
CREATE INDEX idx_cart_items_variant ON cart_items(product_variant_id);

CREATE INDEX idx_vouchers_shop ON vouchers(shop_id);
CREATE INDEX idx_vouchers_active_time ON vouchers(is_active, starts_at, ends_at);
CREATE INDEX idx_vouchers_scope_gin ON vouchers USING GIN (scope_json);

CREATE INDEX idx_orders_customer_created ON orders(customer_id, created_at DESC);
CREATE INDEX idx_orders_status ON orders(order_status);
CREATE INDEX idx_orders_payment_status ON orders(payment_status);
CREATE INDEX idx_orders_created ON orders(created_at);

CREATE INDEX idx_order_items_order ON order_items(order_id);
CREATE INDEX idx_order_items_shop ON order_items(shop_id);
CREATE INDEX idx_order_items_product ON order_items(product_id);
CREATE INDEX idx_order_items_variant ON order_items(product_variant_id);
CREATE INDEX idx_order_items_created ON order_items(created_at);

CREATE INDEX idx_order_vouchers_order ON order_vouchers(order_id);
CREATE INDEX idx_order_vouchers_voucher ON order_vouchers(voucher_id);

CREATE INDEX idx_payments_order ON payments(order_id);
CREATE INDEX idx_payments_status ON payments(payment_status);
CREATE INDEX idx_payments_paid_at ON payments(paid_at);

CREATE INDEX idx_shipments_order ON shipments(order_id);
CREATE INDEX idx_shipments_status ON shipments(shipment_status);
CREATE INDEX idx_shipments_delivered_at ON shipments(delivered_at);

CREATE INDEX idx_returns_customer ON returns(customer_id);
CREATE INDEX idx_returns_order ON returns(order_id);
CREATE INDEX idx_returns_order_item ON returns(order_item_id);
CREATE INDEX idx_returns_status ON returns(return_status);

CREATE INDEX idx_refunds_order ON refunds(order_id);
CREATE INDEX idx_refunds_return ON refunds(return_id);
CREATE INDEX idx_refunds_payment ON refunds(payment_id);
CREATE INDEX idx_refunds_status ON refunds(refund_status);

CREATE INDEX idx_reviews_customer ON reviews(customer_id);
CREATE INDEX idx_reviews_shop ON reviews(shop_id);
CREATE INDEX idx_reviews_product ON reviews(product_id);
CREATE INDEX idx_reviews_status ON reviews(review_status);


-- =====================================================
-- CDC readiness
-- =====================================================

ALTER TABLE app_users REPLICA IDENTITY FULL;
ALTER TABLE user_addresses REPLICA IDENTITY FULL;
ALTER TABLE shops REPLICA IDENTITY FULL;
ALTER TABLE categories REPLICA IDENTITY FULL;
ALTER TABLE products REPLICA IDENTITY FULL;
ALTER TABLE product_variants REPLICA IDENTITY FULL;
ALTER TABLE vouchers REPLICA IDENTITY FULL;
ALTER TABLE orders REPLICA IDENTITY FULL;
ALTER TABLE order_items REPLICA IDENTITY FULL;
ALTER TABLE order_vouchers REPLICA IDENTITY FULL;
ALTER TABLE payments REPLICA IDENTITY FULL;
ALTER TABLE shipments REPLICA IDENTITY FULL;


-- =====================================================
-- DWH notes:
--   dim_customer  <- app_users
--   dim_shop      <- shops
--   dim_category  <- categories
--   dim_product   <- products + product_variants
--   fact_sales    <- orders + order_items
--   fact_payment  <- payments
--   fact_shipment <- shipments
--   fact_return   <- returns
--   fact_refund   <- refunds
--   fact_promo    <- order_vouchers + vouchers
--   fact_review   <- reviews
-- =====================================================

-- =====================================================
-- End of schema-only Learning/MVP Lean file
-- =====================================================
