environment: azure

application:
  logs_path: "/Workspace/Users/2251120184@ut.edu.vn/ecommerce-pipeline/logs"

postgres:
  sslmode: require

spark:
  configure_delta_package: false
  stop_session: false
  config:
    spark.sql.shuffle.partitions: "auto"
    spark.databricks.delta.snapshotPartitions: "2"

lakehouse:
  catalog: "${DATABRICKS_CATALOG}"
  external_root: "${DATABRICKS_EXTERNAL_STORAGE_ROOT}"
  schemas:
    bronze: "${DATABRICKS_BRONZE_SCHEMA}"
    silver: "${DATABRICKS_SILVER_SCHEMA}"
    gold: "${DATABRICKS_GOLD_SCHEMA}"
